### ISSUE TITLE
Need to build out the Settings screens

### ISSUE THREAD

**Issue by twshelton** [Northern-Block/NB_Fortis_Demo#6]
1. Scheduled Scans, set default but allow to change
2. Set notification groups and ways to notify (email, text, etc)
3. File access/permissions (we will wrap around what AF is already using)
4. Move User Activity screen into Settings

**Comment by shivakanyap** [comment]
I have provided menu links for all above screens when user clicks on settings. I have also moved the User Activity screen to the settings now. All other menus are pending.
Can you please provide more details, what needs to be done in point - 1,2,3?

![image](https://user-images.githubusercontent.com/100112547/158597906-2a3cbf36-2124-4c85-9c05-51af0cfcaf1a.png)

**Comment by sdinetz** [comment]
1. Within the File settings menu, can you please remove "File Access" completely? We are leaving this screen out for now.
2. Please also remove the "Scheduled Scans" menu item.
3. Update name of "Notification groups" to "Notifications" - we will provide a screen mockup for this early next week
4. User Activity should appear as it does not, underneath "Notifications" - nothing further with this.

**Comment by sdinetz** [comment]
Everything is complete, except User Activity should appear under Notifications. Thank you!

**Comment by shivakanyap** [comment]
Done

**Comment by sdinetz** [comment]
Complete
