### ISSUE TITLE
ON HOLD: Need development of a popup that appears on the user's screen with file name that has been compromised. 

### ISSUE THREAD

**Issue by twshelton** [Northern-Block/NB_Fortis_Demo#7]
1. Shows file name with .quarantine extension
2. Can this include list of people notified?
3. Include link to Fortis login page

**Comment by sdinetz** [comment]
Will not need a popup, but we will need a notification to a user/group of users. We will clarify and revert with further information.

**Comment by sdinetz** [comment]
Closing this out, everything completed that we need
